In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(np.__version__)

[1 2 3 4]
2.5.2


In [6]:
arr = np.zeros((2,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [18]:
arr = np.ones((2,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [19]:
arr = np.full((2,3), 75)
print(arr)

[[75 75 75]
 [75 75 75]]


In [22]:
arr = np.random.rand(2,3)
print(arr)

[[0.90366738 0.63557089 0.55984808]
 [0.44333295 0.18334181 0.71015804]]


In [23]:
arr = np.random.randint(1,5, size=(2,3))
print(arr)

[[2 1 4]
 [4 4 1]]


In [8]:
arr=np.ones((2,2),dtype=int)
print(arr)

[[1 1]
 [1 1]]


In [10]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [15]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:3])
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

10
50
[20 30]
1
(5,)
int64
5


In [24]:
arr = np.array([[1,2,4],[7,4,2]])
print(arr[0])
print(arr[-1])
print(arr[1:3])
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

[1 2 4]
[7 4 2]
[[7 4 2]]
2
(2, 3)
int64
6


In [28]:
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)
print(new_arr.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [36]:
arr = np.array([1,20,30,40,50,60,70])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

38.714285714285715
40.0
22.06946362034646


In [61]:
a = np.array([10,20,30])
result = []
for x in a:
    result.append(x+5)
print(result)

[np.int64(15), np.int64(25), np.int64(35)]


In [62]:
a = np.array([10,20,30])
result = []
for x in a:
    result.append(int(x)+5)
print(result)

[15, 25, 35]


In [40]:
a = np.array([10,20,30])
result = a + 5
print(result)

[15 25 35]


In [49]:
a = np.array([[10,20,30],[40,50,60]])
result = a * 5
print(result)

[[ 50 100 150]
 [200 250 300]]


In [53]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([10,20,30])
print(a+b)

[[11 22 33]
 [12 23 34]]


In [58]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [63]:
a = np.array([[1],[2]])
b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]]


In [69]:
arr = np.random.randint(1,20,(2,5))
#print(arr)
arr = np.random.choice([10,45,1],2)
print(arr)

[10 45]
